Twf refact python local (#624)
* missing is None  for units

use inversion for a simpler expression

* extra underscore Dispatch

* on.setter must be called on

* use the TreeShr library properly _ and tree.ctx

* cleanup of tree.py

fixed some variable names / typos and some spacing
removed unused import sys
got rid of _statToEx

* moved calcsize("P") and os.name=nt in version

* cleanup __init__

* Fixed descriptorWithProps

EmptyData is not None
should raise error if prop is not convertable by makeData

* added some fuctions and property for compatibility to old api

* cleanup descriptor

use |= and &= and bool
break fields list
id,init,fields

* typos and missing self in event

* unused import and ans->self in apd

* removed _array in mdsarray

* branch in setup is unused.. maybe it was meant to form name

* added TdiCompile etc. for compatibility

* fixed getTags

* remove redundant functions

* replace with Exception as exc

* cleanup test

* use mdsdcl for tcl

* avoid exception

* fixed findPyDevices

* makeData and makeArray

* makeArra and Array.make

* arrayDecompile under Array.decompile()

* make StringArray(list) behave more like compile(str(list))

ans=[b'1\0',b'12\0',b'123']
a=Data.compile(str(ans));print(a)
c=StringArray(ans);print(c)
print(n.array(ans))

* added pointerToObject and made it work

* added Apd functions to test tdi and improved Apd classes

list is faster since list(t) would copy the tuple refs each time on
append and vice versa.
dict and list are already superclasses many methods can be omitted or
optimized

* dclass if $Missing, dclass is 0 -> return None

* hide descriptor

* add EmptyData to dtypeTo(Array)Class

* represent $Missing fromDescriptor and shared instance Missing

* fixed descriptor type for EmptyData aka Missing

serializes to [0,0,0,1,8,0,0,0]

* fixed general MDSplusException name

* update on Apd tdi interfaces

Realizing Apd is no a proper type
The prior version was capable of casting Dicts to lists.
This version allows Lists with one element.
The latter seems more useful for geeric code generation

* generator has no length

efficiently handle generators in py2 and py3

* little more clean up

there is an issue with multidim array which flatten during a
value.descriptor.value cycle

* fixed flags of descriptor_a

* fixed missing opcode handling for compounds like Call

* ctypes takes care of alignment

* fix and optimize Compound

* added check for num of args for Function

* Data.data: removed extra value

evaluate DATA of object should be enough
fixed AttributeError: '???' object has no attribute 'value'

* some fixed and improvements on mdsdata assignTo, setTdiVar, Missing

* fixed decompile, __str__, __repr__ relation

* fixed decompile for Int64 and Uint64

* added apdadd and apdrm plus fixes

* for backward compatibility data need to stay the way it was but get Data actually only calls Data on the argument

Revert "Data.data: removed extra value"
This reverts commit
16c6b85213f6ce29145405099c49e319af59c30d.

* evaluate one layer before adding to be consistent with constructors

* Signal broke old implementation by alterint the __getitem__ method